Repository milieuinfo/webcomponent-vl-ui-search-results, pull requests merged in 2020-07, with the labels that each got.

#3 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#4 Update dependency vl-ui-core to v5.6.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#5 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#7 Alleen content slot elementen van type dl moeten automatisch voorzien worden van classes
  demo/vl-search-results.html
  dist/style.css
  dist/style.scss
  dist/vl-search-result.js
  dist/vl-search-result.min.js
  dist/vl-search-result.src.js
  dist/vl-search-results.min.js
  dist/vl-search-results.src.js
  src/style.css
  src/style.scss
  src/vl-search-result.js
  test/e2e/components/vl-search-result.js
  test/e2e/pages/vl-search-results.page.js
  test/e2e/search-results.test.js
  test/unit/vl-search-result.test.html
Labels: bug

#8 Update dependencies
  package-lock.json
  package.json
Labels: chore

#9 Introductie e2e functie om zoekresultaten te bekomen
  test/e2e/components/vl-search-results.js
Labels: chore
